USE [flight-delays]
GO

SELECT *
FROM dbo.airlines;

SELECT *
FROM dbo.airports;

SELECT TOP 10 *
FROM dbo.flights;

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'flights';

-- ADDING DATE TABLE AS COMBINATION OF YEAR MONTH AND DAY

ALTER TABLE dbo.flights
ADD DATE_NEW DATE;

UPDATE dbo.flights
SET DATE_NEW = CAST(CONCAT(YEAR, '-', RIGHT('0' + MONTH, 2), '-', RIGHT('0' + DAY, 2)) AS DATE);

-- DEALING WITH BLANK VALUES

SELECT FLIGHT_NUMBER
FROM dbo.flights;

SELECT  TOP 10 *
FROM dbo.flights;

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'flights';


-- CONVERTING DAY_OF_WEEK TO TINYINT

ALTER TABLE dbo.flights
ALTER COLUMN DAY_OF_WEEK TINYINT;


-- CONVERTING DAY_OF_WEEK TO VARCHAR(10)

ALTER TABLE dbo.flights
ALTER COLUMN AIRLINE VARCHAR(10);


-- CONVERTING DAY_OF_WEEK TO VARCHAR(10)

ALTER TABLE dbo.flights
ALTER COLUMN FLIGHT_NUMBER VARCHAR(10);

-- CONVERTING TAIL_NUMBER TO VARCHAR(20)

ALTER TABLE dbo.flights
ALTER COLUMN TAIL_NUMBER VARCHAR(20);

-- CONVERTING ORIGIN_AIRPORT, DESTINATION_AIRPORT TO VARCHAR(20)

ALTER TABLE dbo.flights
ALTER COLUMN ORIGIN_AIRPORT VARCHAR(10);

ALTER TABLE dbo.flights
ALTER COLUMN DESTINATION_AIRPORT VARCHAR(10);

-- CONVERTING SCHEDULED_DEPARTURE, DEPARTURE_TIME, WHEELS_OFF, WHEELS_ON, SCHEDULED_ARRIVAL, ARRIVAL_TIME TO TIME

ALTER TABLE dbo.flights
ADD SCHEDULED_DEPATURE_TIME
	AS ( CAST(
	RIGHT('00' + CAST(Scheduled_Departure / 100 AS VARCHAR(4)), 2) + ':' +
	RIGHT('00' + CAST(Scheduled_Departure % 100 AS VARCHAR(2)), 2) + ':00' AS TIME                --  NAME TO BE CHANGED 
	));

ALTER TABLE  dbo.flights
DROP COLUMN Scheduled_Departure_Time;



ALTER TABLE dbo.flights
ADD ACTUAL_DEPARTURE_TIME
	AS ( CAST(
	RIGHT('00' + CAST(DEPARTURE_TIME / 100 AS VARCHAR(4)), 2) + ':' +
	RIGHT('00' + CAST(DEPARTURE_TIME % 100 AS VARCHAR(2)), 2) + ':00' AS TIME
	));


ALTER TABLE dbo.flights
ADD ARRIVAL_TIME_TIME
	AS ( CAST(                                                                                        --- NAME TO BE CHANGED 
	RIGHT('00' + CAST(ARRIVAL_TIME / 100 AS VARCHAR(4)), 2) + ':' +
	RIGHT('00' + CAST(ARRIVAL_TIME % 100 AS VARCHAR(2)), 2) + ':00' AS TIME
	));

ALTER TABLE  dbo.flights
DROP COLUMN TIME;



ALTER TABLE dbo.flights
ADD WHEELS_OFF_TIME
	AS ( CAST(
	RIGHT('00' + CAST(WHEELS_OFF / 100 AS VARCHAR(4)), 2) + ':' +
	RIGHT('00' + CAST(WHEELS_OFF % 100 AS VARCHAR(2)), 2) + ':00' AS TIME
	));

ALTER TABLE dbo.flights
ADD WHEELS_ON_TIME
	AS ( CAST(
	RIGHT('00' + CAST(WHEELS_ON / 100 AS VARCHAR(4)), 2) + ':' +
	RIGHT('00' + CAST(WHEELS_ON % 100 AS VARCHAR(2)), 2) + ':00' AS TIME
	));



ALTER TABLE dbo.flights
ADD SCHEDULED_ARRIVAL_TIME
	AS ( CAST(
	RIGHT('00' + CAST(SCHEDULED_ARRIVAL / 100 AS VARCHAR(4)), 2) + ':' +
	RIGHT('00' + CAST(SCHEDULED_ARRIVAL % 100 AS VARCHAR(2)), 2) + ':00' AS TIME
	));




-- CONVERTING DEPARTURE_DELAY, ARRIVAL_DELAY TO INT

ALTER TABLE dbo.flights
ALTER COLUMN DEPARTURE_DELAY INT;


ALTER TABLE dbo.flights
ALTER COLUMN ARRIVAL_DELAY INT;


-- Replacing NULLs from DEPARTURE_DELAY and ARRIVAL_DELAY :

SELECT DEPARTURE_DELAY
FROM dbo.flights;

SELECT COUNT(*) NULL_DEPARTURE_DELAY
FROM dbo.flights
WHERE DEPARTURE_DELAY IS NULL;


SELECT ARRIVAL_DELAY
FROM dbo.flights;

SELECT COUNT(*) NULL_ARRIVAL_DELAY
FROM dbo.flights
WHERE ARRIVAL_DELAY IS NULL;


